image:
  tag: ${image_tag}

serviceAccount:
  create: true
  name: ${service_account_name}

resources: ${jsonencode(resources)}

orgWhitelist: ${jsonencode(org_whitelist)}

atlantisUrl: ${webhook_url}

vcsSecret: ${jsonencode({
  github = {
    token = "$ATLANTIS_GH_TOKEN"
    webhookSecret = "$ATLANTIS_GH_WEBHOOK_SECRET"
  }
  gitlab = {
    token = "$ATLANTIS_GITLAB_TOKEN"
    webhookSecret = "$ATLANTIS_GITLAB_WEBHOOK_SECRET"
  }
})}

aws:
  region: ${aws_region}
  credentials:
    secretName: "${local.name}-secrets"
    accessKey: AWS_ACCESS_KEY_ID
    secretKey: AWS_SECRET_ACCESS_KEY

repoConfig: $ATLANTIS_REPO_CONFIG

persistent:
  enabled: true
  storageClass: ${storage_class}
  size: ${storage_size}

ingress:
  enabled: ${ingress_enabled}
  %{ if ingress_enabled }
  annotations: ${jsonencode(ingress_annotations)}
  hosts:
    - host: ${ingress_host}
      paths:
        - path: /
          pathType: Prefix
  %{ endif }